openapi: 3.0.0
info:
  title: Etymology Search
  version: 0.0.0
servers:
  - url: 'http://etymology-search'
    description: for development
paths:
  /etymologies/{word}:
    get:
      summary: get the etymology of an English word
      parameters:
        - in: path
          name: word
          schema: 
            type: string
            example: approximate
          required: true
          description: 'English word'
      responses:
        200:
          description: 'HTTP code 200'
          content:
            application/json:
              schema:
                type: object
                properties:
                  etymology_text:
                    type: string
                    example: 'late Middle English (in the adjectival sense ‘close, similar’): from late Latin approximatus, past participle of approximare, from ad- ‘to’ + proximus ‘very near’. The verb (originally meaning ‘bring close’) arose in the mid 17th century; the current adjectival sense dates from the early 19th century'
                  etymologies:
                    $ref: '#/components/schemas/Etymologies'
components:
  schemas:
    WordData:
      type: object
      properties:
        word:
          type: string
          example: approximate
        part_of_speech:
          type: string
          example: adjective
        meaning:
          type: string
          example: close to the actual, but not completely accurate or exact
        etymology_text:
          type: string
          example: 'late Middle English (in the adjectival sense ‘close, similar’): from late Latin approximatus, past participle of approximare, from ad- ‘to’ + proximus ‘very near’. The verb (originally meaning ‘bring close’) arose in the mid 17th century; the current adjectival sense dates from the early 19th century'
        etymologies:
          type: array
          $ref: '#/components/schemas/Etymologies'
    Etymologies:
      type: array
      items:
        type: object
        properties:
          prefix:
            $ref: '#/components/schemas/prefix'
          root:
            $ref: '#/components/schemas/Root'
          suffix:
            $ref: '#/components/schemas/Suffix'
    prefix:
      type: object
      properties:
        prefix:
          type: string
          example: ad-
        meaning:
          type: string
          example: 'to'
    Root:
      type: object
      properties:
        root:
          type: string
          example: proximus
        meaning:
          type: string
          example: 'very near'
    Suffix:
      type: object
      properties:
        suffix:
          type: string
          example: -ate
        meaning:
          type: string
          example: 'to N/V/adj'